language: node_js

os: linux
dist: bionic

node_js:
  - 10.15.3
  - lts/*

cache: npm

before_install:
  - npm install -g npm@latest
install:
  - npm install

script:
  - npm test
  - npm run security-checks
